### ISSUE TITLE
命名修改

### ISSUE THREAD

**Issue by jaysdev** [marktony/ZhiHuDaily#1]
你好。utils包和ui包的包名换成小写吧，编译报错。

**Comment by marktony** [comment]
好的

**Comment by marktony** [comment]
#1

已经修改，并且compile sdk已经全部升级至最新的24 可能需要重新编译

**Comment by jaysdev** [comment]
:100:

**Comment by marktony** [comment]
如果下载的zip仍然不能编译的话 可以试着手动修改包的名称
大致的记录为 UI --> ui  Utils --> utils Adapters --> adapters Interfaces --> interfaces Behavior --> behavior
特别需要注意的是在fragment_latest.xml中引用了一个fab的行为，注意这里的包名也需要修改
如果仍然不行的话 可以给我发邮件或者提issue即可
我之前确实修改了包名 但是github上好像有一部分包名并没有变化 @jaysdev
