### ISSUE TITLE
支持一下

### ISSUE THREAD

**Issue by atfa** [marktony/ZhiHuDaily#4]
很喜欢这个项目。
但是google play因为我下载了这个项目，居然又给我推荐了一个叫做卡片新闻的客户端。内容比咱多，是个强劲的对手，也是很好的学习对象。
加油！

**Comment by marktony** [comment]
嗯嗯  那个app做的确实好 不过其实纸飞机和那个app的定位不同啦 那个app的定位应该是新闻 这个更多的是杂志什么的  不过确实值得学习   另外，蟹蟹你的支持哟！
